from django.urls import path
from .views import (
    # login,
    signup,
    oauth,
    edit_name,
    refresh_tokens,
    get_2fa_qr_code,
    verify_otp,
    enable_2fa,
    disable_2fa,
    is_2fa_enabled,
    get_current_user_info,
    get_user_info,
    get_users,
    edit_password,
    is_oauth,
    check_session,
    logout,
    friend_user_request,
    add_friend,
    fetch_notifications,
    accept_friend_request,
    decline_friend_request,
    send_game_invite,
    accept_game_invite,
    decline_game_invite,
    is_friend,
    delete_account,
    upload_avatar,
    accept_final_game_invite,
    edit_nickname,
    get_nickname,
    is_online,
    can_access_2fa,
    players_leaderboard
)
from .views.auth import login

urlpatterns = [
    path("login", login),
    path("signup", signup),
    path("oauth", oauth),
    path("refresh", refresh_tokens),
    path("edit_name", edit_name),
    path("2fa_qr_code", get_2fa_qr_code),
    path("verify_otp", verify_otp),
    path("enable_2fa", enable_2fa),
    path("disable_2fa", disable_2fa),
    path("is_2fa_enabled", is_2fa_enabled),
    path("get_current_user_info", get_current_user_info),
    path("get_user_info", get_user_info),
    path("get_users", get_users),
    path("edit_password", edit_password),
    path("is_oauth", is_oauth),
    path("check_session", check_session),
    path("logout", logout),
    path("friends", friend_user_request),
    path("add_friend", add_friend),
    path("accept_friend_request", accept_friend_request),
    path("decline_friend_request", decline_friend_request),
    path("fetch_notifications", fetch_notifications),
    path("send_game_invite", send_game_invite),
    path("accept_game_invite", accept_game_invite),
    path("decline_game_invite", decline_game_invite),
    path("is_friend", is_friend),
    path("delete_account", delete_account),
    path("upload_avatar", upload_avatar),
    path("accept_final_game_invite", accept_final_game_invite),
    path("edit_nickname", edit_nickname),
    path("get_nickname", get_nickname),
    path("is_online", is_online),
    path("can_access_2fa", can_access_2fa),
    path("players_leaderboard", players_leaderboard),
]
